-- ============================================================
-- Phase 2: Product category tree
-- Generated: 2026-04-26T22:00:45.028Z
-- ============================================================

INSERT INTO product_categories (name, parent_category_id, usda_fdc_id) VALUES
  ('Poultry Products', NULL, 5),
  ('Beef Products', NULL, 13),
  ('Dairy and Egg Products', NULL, 1),
  ('Vegetables and Vegetable Products', NULL, 11),
  ('Fruits and Fruit Juices', NULL, 9),
  ('Cereal Grains and Pasta', NULL, 20),
  ('Legumes and Legume Products', NULL, 16),
  ('Baked Products', NULL, 18),
  ('Fats and Oils', NULL, 4),
  ('Soups, Sauces, and Gravies', NULL, 6),
  ('Sweets', NULL, 19),
  ('Beverages', NULL, 14),
  ('Finfish and Shellfish Products', NULL, 15),
  ('Frozen Vegetables', NULL, NULL);

INSERT INTO product_categories (name, parent_category_id, usda_fdc_id) VALUES
  ('Chicken, raw', (SELECT category_id FROM product_categories WHERE name='Poultry Products'), NULL),
  ('Ground beef, raw', (SELECT category_id FROM product_categories WHERE name='Beef Products'), NULL),
  ('Milk', (SELECT category_id FROM product_categories WHERE name='Dairy and Egg Products'), NULL),
  ('Eggs', (SELECT category_id FROM product_categories WHERE name='Dairy and Egg Products'), NULL),
  ('Butter', (SELECT category_id FROM product_categories WHERE name='Dairy and Egg Products'), NULL),
  ('Cheese', (SELECT category_id FROM product_categories WHERE name='Dairy and Egg Products'), NULL),
  ('Yogurt', (SELECT category_id FROM product_categories WHERE name='Dairy and Egg Products'), NULL),
  ('Sour cream', (SELECT category_id FROM product_categories WHERE name='Dairy and Egg Products'), NULL),
  ('Cream cheese', (SELECT category_id FROM product_categories WHERE name='Dairy and Egg Products'), NULL),
  ('Potatoes', (SELECT category_id FROM product_categories WHERE name='Vegetables and Vegetable Products'), NULL),
  ('Onions', (SELECT category_id FROM product_categories WHERE name='Vegetables and Vegetable Products'), NULL),
  ('Carrots', (SELECT category_id FROM product_categories WHERE name='Vegetables and Vegetable Products'), NULL),
  ('Broccoli', (SELECT category_id FROM product_categories WHERE name='Vegetables and Vegetable Products'), NULL),
  ('Spinach', (SELECT category_id FROM product_categories WHERE name='Vegetables and Vegetable Products'), NULL),
  ('Canned tomatoes', (SELECT category_id FROM product_categories WHERE name='Vegetables and Vegetable Products'), NULL),
  ('Canned beans', (SELECT category_id FROM product_categories WHERE name='Legumes and Legume Products'), NULL),
  ('Dried beans', (SELECT category_id FROM product_categories WHERE name='Legumes and Legume Products'), NULL),
  ('Bananas', (SELECT category_id FROM product_categories WHERE name='Fruits and Fruit Juices'), NULL),
  ('Apples', (SELECT category_id FROM product_categories WHERE name='Fruits and Fruit Juices'), NULL),
  ('Orange juice', (SELECT category_id FROM product_categories WHERE name='Fruits and Fruit Juices'), NULL),
  ('Apple juice', (SELECT category_id FROM product_categories WHERE name='Fruits and Fruit Juices'), NULL),
  ('Rice', (SELECT category_id FROM product_categories WHERE name='Cereal Grains and Pasta'), NULL),
  ('Pasta', (SELECT category_id FROM product_categories WHERE name='Cereal Grains and Pasta'), NULL),
  ('Oats', (SELECT category_id FROM product_categories WHERE name='Cereal Grains and Pasta'), NULL),
  ('Breakfast cereal', (SELECT category_id FROM product_categories WHERE name='Cereal Grains and Pasta'), NULL),
  ('Ramen noodles', (SELECT category_id FROM product_categories WHERE name='Cereal Grains and Pasta'), NULL),
  ('Bread', (SELECT category_id FROM product_categories WHERE name='Baked Products'), NULL),
  ('Tortillas', (SELECT category_id FROM product_categories WHERE name='Baked Products'), NULL),
  ('Flour', (SELECT category_id FROM product_categories WHERE name='Baked Products'), NULL),
  ('Olive oil', (SELECT category_id FROM product_categories WHERE name='Fats and Oils'), NULL),
  ('Vegetable oil', (SELECT category_id FROM product_categories WHERE name='Fats and Oils'), NULL),
  ('Pasta sauce', (SELECT category_id FROM product_categories WHERE name='Soups, Sauces, and Gravies'), NULL),
  ('Broth', (SELECT category_id FROM product_categories WHERE name='Soups, Sauces, and Gravies'), NULL),
  ('Canned soup', (SELECT category_id FROM product_categories WHERE name='Soups, Sauces, and Gravies'), NULL),
  ('Peanut butter', (SELECT category_id FROM product_categories WHERE name='Legumes and Legume Products'), NULL),
  ('Jelly and jam', (SELECT category_id FROM product_categories WHERE name='Sweets'), NULL),
  ('Sugar', (SELECT category_id FROM product_categories WHERE name='Sweets'), NULL),
  ('Coffee', (SELECT category_id FROM product_categories WHERE name='Beverages'), NULL),
  ('Canned tuna', (SELECT category_id FROM product_categories WHERE name='Finfish and Shellfish Products'), NULL),
  ('Mayonnaise', (SELECT category_id FROM product_categories WHERE name='Soups, Sauces, and Gravies'), NULL),
  ('Ketchup', (SELECT category_id FROM product_categories WHERE name='Soups, Sauces, and Gravies'), NULL),
  ('Mustard', (SELECT category_id FROM product_categories WHERE name='Soups, Sauces, and Gravies'), NULL),
  ('Frozen peas', (SELECT category_id FROM product_categories WHERE name='Frozen Vegetables'), NULL),
  ('Frozen corn', (SELECT category_id FROM product_categories WHERE name='Frozen Vegetables'), NULL);
