import type { MatchResponse } from '@/lib/api/compare';

export const mockResult: MatchResponse = {
  receipt: {
    store_name: 'Safeway',
    store_address: '500 Greenville Rd, Livermore CA 94550',
    receipt_date: '2026-04-25  14:37',
    receipt_total: 31.83,
    item_count: 6,
  },
  chain_detected: 'safeway',
  parse_source: 'heuristic',
  parsed: { items: [] },
  schema_warnings: [],
  location_default: null,
  radius_miles_default: null,
  summary: { total_items: 6, compare_items: 6, matched: 5, unmatched: 1 },
  items: [
    {
      line_index: 0,
      raw_text: '3@ GINOS BLEU 4OZ',
      description: 'gino\'s blue cheese 4 oz',
      description_raw: 'GINOS BLEU 4OZ',
      code: '021000061121',
      quantity: 3,
      unit: 'each',
      unit_price: 4.99,
      shelf_price: 14.97,
      member_price: 11.97,
      is_store_brand: true,
      item_type: 'compare',
      annotations: [
        { field: 'description', original: 'CH', interpreted: 'chip', method: 'abbreviation_dict' },
      ],
      llm_interpretation: {
        product_name: "Gino's Blue Cheese, 4 oz",
        brand_guess: "Gino's",
        size_guess: '4 oz',
        reasoning:
          "Interpreted '3@ GINOS BLEU 4OZ' as 3 units of Gino's Blue Cheese 4 oz packages. '3@' is the multi-buy prefix; 'BLEU' = blue cheese.",
        confidence: 'high',
        is_produce_or_generic: false,
      },
      suggested_match: {
        source: 'off',
        barcode: '0001234567890',
        name: "Gino's Blue Cheese Crumbles",
        brand: "Gino's",
        package_size: 4,
        package_unit: 'oz',
        reason: "Exact match for Gino's Blue Cheese, 4 oz package.",
        match_confidence: 'high',
        enrichment: null,
      },
      candidates: [
        {
          source: 'off',
          barcode: '0001234567890',
          name: "Gino's Blue Cheese Crumbles",
          brand: "Gino's",
          quantity_raw: '4 oz',
          package_size: 4,
          package_unit: 'oz',
          image_url: null,
          score: 0.92,
        },
      ],
      match_method: 'llm',
    },
    {
      line_index: 1,
      raw_text: 'SAFWY BFLS CKNG THGH 2.13LB',
      description: 'boneless skinless chicken thighs 2.13 lb',
      description_raw: 'SAFWY BFLS CKNG THGH',
      code: '202113',
      quantity: 2.13,
      unit: 'lb',
      unit_price: 3.47,
      shelf_price: 7.39,
      member_price: 4.46,
      is_store_brand: true,
      item_type: 'compare',
      annotations: [
        { field: 'brand', original: 'POUND PLUS', interpreted: "Trader Joe's", method: 'brand_prefix' },
        { field: 'size', original: 'POUND PLUS', interpreted: '1 lb', method: 'size_regex' },
      ],
      llm_interpretation: {
        product_name: 'Boneless Skinless Chicken Thighs',
        brand_guess: 'Safeway',
        size_guess: '2.13 lb',
        reasoning:
          "BFLS=boneless, CKNG=chicken, THGH=thigh. SAFWY prefix indicates Safeway store brand. 2.13 lb is the weight purchased priced at $3.47/lb.",
        confidence: 'high',
        is_produce_or_generic: false,
      },
      suggested_match: {
        source: 'in-house',
        canonical_id: 17,
        name: 'Boneless Skinless Chicken Thighs',
        brand: null,
        pricing_unit: 'per_lb',
        reason: 'Exact match for boneless skinless chicken thighs (per lb).',
        match_confidence: 'high',
        enrichment: null,
      },
      candidates: [
        {
          source: 'in-house',
          canonical_id: 17,
          name: 'Boneless Skinless Chicken Thighs',
          brand: null,
          package_size: null,
          package_unit: null,
          pricing_unit: 'per_lb',
          score: 0.88,
          image_url: null,
        },
      ],
      match_method: 'llm',
    },
    {
      line_index: 2,
      raw_text: 'BANANAS',
      description: 'bananas',
      description_raw: 'BANANAS',
      code: '4011',
      quantity: 1.5,
      unit: 'lb',
      unit_price: 0.59,
      shelf_price: 0.89,
      member_price: 0.89,
      is_store_brand: false,
      item_type: 'compare',
      annotations: [],
      llm_interpretation: {
        product_name: 'Bananas',
        brand_guess: null,
        size_guess: null,
        reasoning: 'Generic produce item — no meaningful brand or barcode.',
        confidence: 'high',
        is_produce_or_generic: true,
      },
      suggested_match: {
        source: 'in-house',
        canonical_id: 42,
        name: 'Bananas',
        pricing_unit: 'per_lb',
        reason: 'Generic produce. Canonical "Bananas" is the right match.',
        match_confidence: 'high',
        enrichment: null,
      },
      candidates: [
        {
          source: 'in-house',
          canonical_id: 42,
          name: 'Bananas',
          brand: null,
          package_size: null,
          package_unit: null,
          pricing_unit: 'per_lb',
          score: 0.95,
          image_url: null,
        },
      ],
      match_method: 'canonical_fallback',
    },
    {
      line_index: 3,
      raw_text: 'ORG STRWBRY 1LB',
      description: 'organic strawberries 1 lb',
      description_raw: 'ORG STRWBRY 1LB',
      code: null,
      quantity: 1,
      unit: null,
      unit_price: null,
      shelf_price: 4.49,
      member_price: 4.49,
      is_store_brand: false,
      item_type: 'compare',
      annotations: [
        { field: 'organic', original: 'ORG', interpreted: 'organic', method: 'organic_flag' },
        { field: 'description', original: 'STRWBRY', interpreted: 'strawberry', method: 'abbreviation_dict' },
        { field: 'size', original: '1LB', interpreted: '1 lb', method: 'size_regex' },
      ],
      llm_interpretation: {
        product_name: 'Organic Strawberries (1 lb)',
        brand_guess: null,
        size_guess: '1 lb',
        reasoning: "Standard 1 lb organic strawberry clamshell. 'ORG' is the organic flag, 'STRWBRY' expanded to strawberry.",
        confidence: 'medium',
        is_produce_or_generic: true,
      },
      suggested_match: {
        source: 'in-house',
        canonical_id: 88,
        name: 'Organic Strawberries',
        pricing_unit: 'per_each',
        reason: 'Best match for 1 lb organic strawberry clamshell.',
        match_confidence: 'medium',
        enrichment: null,
      },
      candidates: [
        {
          source: 'in-house',
          canonical_id: 88,
          name: 'Organic Strawberries',
          brand: null,
          package_size: 1,
          package_unit: 'lb',
          pricing_unit: 'per_each',
          score: 0.78,
          image_url: null,
        },
      ],
      match_method: 'llm',
    },
    {
      line_index: 4,
      raw_text: 'WHL MLK 1G',
      description: 'whole milk 1 gal',
      description_raw: 'WHL MLK 1G',
      code: null,
      quantity: 1,
      unit: null,
      unit_price: null,
      shelf_price: 5.99,
      member_price: 5.99,
      is_store_brand: true,
      item_type: 'compare',
      annotations: [
        { field: 'description', original: 'WHL', interpreted: 'whole', method: 'abbreviation_dict' },
        { field: 'description', original: 'MLK', interpreted: 'milk', method: 'abbreviation_dict' },
        { field: 'size', original: '1G', interpreted: '1 gal', method: 'size_regex' },
      ],
      llm_interpretation: {
        product_name: 'Whole Milk, 1 gallon',
        brand_guess: "Trader Joe's",
        size_guess: '1 gal',
        reasoning: "Standard whole milk gallon. 'WHL'→whole, 'MLK'→milk, '1G'→1 gallon.",
        confidence: 'high',
        is_produce_or_generic: false,
      },
      suggested_match: {
        source: 'in-house',
        canonical_id: 12,
        name: 'Whole Milk',
        pricing_unit: 'per_gal',
        reason: 'Exact match for whole milk, 1 gallon.',
        match_confidence: 'high',
        enrichment: null,
      },
      candidates: [
        {
          source: 'in-house',
          canonical_id: 12,
          name: 'Whole Milk',
          brand: null,
          package_size: 1,
          package_unit: 'gal',
          pricing_unit: 'per_gal',
          score: 0.91,
          image_url: null,
        },
      ],
      match_method: 'llm',
    },
    {
      line_index: 5,
      raw_text: 'MYSTERY ITEM XYZ',
      description: 'mystery item xyz',
      description_raw: 'MYSTERY ITEM XYZ',
      code: null,
      quantity: null,
      unit: null,
      unit_price: null,
      shelf_price: 22.51,
      member_price: 22.51,
      is_store_brand: false,
      item_type: 'compare',
      annotations: [],
      llm_interpretation: {
        product_name: 'Unknown product',
        brand_guess: null,
        size_guess: null,
        reasoning: "Couldn't confidently interpret this line — too few signals.",
        confidence: 'low',
        is_produce_or_generic: false,
      },
      suggested_match: null,
      candidates: [],
      match_method: 'llm',
    },
  ],
};
